gh-387 - scaffold submission service
MauroDataMapper/mdm-explorer pull request #400
Opened 2024-05-09 16:08 UTC by abwilson23

- Create initial implementation of the overall submission process flow including: interfaces, main submission control flow, generic step stub and basic testing. 
- slight start to the select project step just to have a step to test. 

closes #387

2024-05-10 09:02 UTC, NigelPalmer requested changes
This is looking like a good start, well done!

Now we have this in place, I would like to take this task a little further to prove that the submission service will behave in the way that we would like. To that end, please update the task with the following functionality:

1. Change the "Select Project Dialog" to be a dialog with a button on it that says "Click to complete step 1". When clicked the specification description should be updated with the text "Submission Step 1 Complete". 
2. Update `SelectProjectStep.run` so that the stepResult includes a string called `whatStep1Did`. Set `whatStep1Did` to the message "Step 1 ran this time"
3. Update `SelectProjectStep.isRequired` to check the specification description:
If the description includes the text "Submission Step 1 Complete",  set `isRequired` to false and set `whatStep1Did` to "Step 1 was not required to be run".
If the description _does not_ include the text "Submission Step 1 Complete", set `isRequired` to true 
4. Create a Step 2. Step 2 should simply show a dialog that displays the  `whatStep1Did` message.

Regarding code review, nothing major has leapt out yet, but I would rather carry out a more thorough code rerview once the above is complete.

Apologies for moving the goal posts, but I think this will be worth doing.

2024-05-14 09:26 UTC, NigelPalmer requested changes
This was not quite what I had in mind, but the implementation clearly shows the step process working. Provided I type in "Submission step 1 complete." into the dialog, then the subsequent steps will fast track to step 2. If anything else is typed, then step 1 is run again. This is good and shows everything working as it should.

There are a couple of code observations that need addressing.

2024-05-14 09:26 UTC, NigelPalmer commented on src/app/data-explorer/specification-submission/submission-steps/select-project.step.ts
> +import { Observable, map, of, switchMap, tap } from 'rxjs';
switchMap is not used. This will fail linting.

2024-05-14 09:26 UTC, NigelPalmer commented on src/app/data-explorer/specification-submission/submission-steps/select-project.step.ts
> +      isRequired: isRequired,
'Expected property shorthand' error is being shown in my Visual Studio Code. Please change to just be isRequired.

2024-05-14 09:26 UTC, NigelPalmer commented on src/app/data-explorer/specification-submission/submission-steps/select-project.step.ts
> +              isRequired: false,
Why is isRequired being set to false here? This is confusing to follow. What is this isRequired even being used for after this point? Could we not just default isRequired to false in the StepResult and therefore not set the value here?

2024-05-14 09:26 UTC, NigelPalmer commented on src/app/data-explorer/specification-submission/submission.resource.ts
> +  | 'SaveDataRequest';
The idea of StepName was that it is something that would be displayed to the user when a submission is running. Therefore these should be sentence case rather than looking code like. e.g:
'Select project'
'Get Data Request'
'Generate SQL file'
etc

2024-05-14 09:44 UTC, abwilson23 commented on src/app/data-explorer/specification-submission/submission-steps/select-project.step.ts
> +import { Observable, map, of, switchMap, tap } from 'rxjs';
Resolved.

2024-05-14 09:44 UTC, abwilson23 commented on src/app/data-explorer/specification-submission/submission-steps/select-project.step.ts
> +      isRequired: isRequired,
Resolved.

2024-05-14 10:12 UTC, abwilson23 commented on src/app/data-explorer/specification-submission/submission.resource.ts
> +  | 'SaveDataRequest';
Changed.

2024-05-14 10:13 UTC, abwilson23 commented on src/app/data-explorer/specification-submission/submission-steps/select-project.step.ts
> +              isRequired: false,
I went with removing it altogether as only the result is used in the main submit method to save any new data to the state.

2024-05-14 10:32 UTC, NigelPalmer approved these changes
This framework is now ready to be populated with steps. This is all working well and a simple and flexible framework.

2024-05-14 10:32 UTC, merged