gh-412 - Add user friendly dialog if submission of data specification fails.
MauroDataMapper/mdm-explorer pull request #415
Opened 2024-07-04 16:15 UTC by abwilson23

- Add `SimpleDialogComponent` for generic dialog messages. 
- Add a test checking the dialog is opened if an error is thrown during a test. 

closes #412

2024-07-19 15:45 UTC, NigelPalmer requested changes

2024-07-19 15:45 UTC, NigelPalmer commented on src/app/data-explorer/specification-submission/services/specification-submission.service.ts
> +    If you keep seeing this message then please contact Mauro administrators for help.</p>`;
We are no longer showing a useful error message to the user. I just tried to submit and the user facing message told me to simply try again. Where as the console message said "NoProjectsFoundError: You do not have any projects to submit this data request for." What we need to do is display the errors that we know are user friendly, otherwise default to the current behaviour of "Please try again". I.e `if NoProjectsFoundError then display error message in dialog`

It should look something like this:
![image](https://github.com/user-attachments/assets/7f2cee0f-2448-4a5f-a535-ebd0c8b24d2a)

You may need to update the returned error message to include the additional text. Also there may be other exception types that we should be displaying the error message for.

2024-07-23 08:46 UTC, abwilson23 commented on src/app/data-explorer/specification-submission/services/specification-submission.service.ts
> +    If you keep seeing this message then please contact Mauro administrators for help.</p>`;
NoProjectsFoundError now produces a friendly message explaining how the user can action the issue on their own. All other errors default to a standard error message from the original ticket as the fixes are outside the control of the user. 
Simple to add further modifications to error handling if necessary.

2024-07-23 16:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MauroDataMapper/mdm-explorer?pullRequest=415) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MauroDataMapper/mdm-explorer?pullRequest=415) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: abwilson23<br/>:x: CORP\Nigel.Palmer<br/><hr/>**CORP\Nigel.Palmer** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MauroDataMapper/mdm-explorer?pullRequest=415) it.</sub>

2024-09-23 15:31 UTC, NigelPalmer approved these changes
User receives a clear message telling them what they need to do. We will likely need to update the wording in the future as the workflow changes, but the message we have now is accurate for the current state of the system.

2024-09-23 15:31 UTC, merged